import { OrbData } from '../types';

const APOD_VIDEO_SRC = new URL('../../apod-vid.mp4', import.meta.url).href;
const MAGNETIC_VIDEO_SRC = new URL('../../2015-magnetic.mp4', import.meta.url).href;

export const REPORT_ORBS: OrbData[] = [
  {
    id: 1,
    orbLabel: 'Introduction',
    modalTitle: 'Introduction',
    x: 12,
    y: 18,
    size: 62,
    figure: {
      label: 'Figure 1',
      placeholder: 'Insert APOD image here',
      videoSrc: APOD_VIDEO_SRC,
      caption:
        'Representative frame from NASA’s APOD video Coronal Rain on the Sun (27 May 2018). The still from the time-lapse ultraviolet footage shows cooled plasma cascading back toward the Sun along magnetic field lines following the July 2012 eruption. Each second of footage represents approximately six minutes of real time. Source: NASA/SDO/SVS/GSFC (NASA 2018).',
    },
    paragraphs: [
      `On 19 July 2012, NASA's Solar Dynamics Observatory recorded something that looks, at first glance, almost tranquil (NASA 2018). Ribbons of glowing material drift downward across the Sun's limb in long, curving arcs, tracing invisible pathways the way water finds its course over a hillside. Time is compressed, six minutes squeezed into every second, and the motion is hypnotic. But this is not water, and the scale is staggering: each arc stretches several times the diameter of Earth, and the “droplets” are clumps of ionised gas glowing at around 50,000 Kelvin, hotter than any flame humans can produce.`,
      `What you are watching is coronal rain. The footage is recorded in ultraviolet light, invisible to our eyes but ideally suited to imaging the Sun's atmosphere, its outer layers are nearly transparent at visible wavelengths, while they glow brightly in the extreme ultraviolet. Switching wavelength is like switching on a torch in a dark room: whole structures that were hidden suddenly become visible. That is one of the quiet lessons of the APOD video, different parts of the electromagnetic spectrum reveal different parts of the Sun.`,
      `Coronal rain is beautiful. It is also a clue. Inside these gentle cascades lies one of the oldest unsolved puzzles in solar physics, a question scientists have been grappling with for seven decades, and one that recent spacecraft are only just beginning to crack.`,
    ],
  },
  {
    id: 2,
    orbLabel: 'The Corona and Its Deepest Mystery',
    modalTitle: 'The Corona and Its Deepest Mystery',
    x: 31,
    y: 10,
    size: 80,
    paragraphs: [
      `The rain falls from the Sun's outer atmosphere, a region whose physics has been quietly embarrassing scientists for generations. The Sun has no solid surface. It is a layered ball of plasma, and the part we see with our eyes, the photosphere, sits at around 5,500 °C, hot enough to vaporise any known material (NASA 2024a). Above it lies a thin layer called the chromosphere, and beyond that stretches the corona, the farthest part of the solar atmosphere.`,
      `Here, ordinary intuition breaks down. The corona usually sits between one and three million degrees Celsius, and active regions during solar flares can exceed ten million (Reale 2014). The upper atmosphere burns hundreds of times hotter than the surface below it, imagine a campfire where the air a metre above the flames is hotter than the flames themselves, and you have roughly the scale of the problem.`,
      `This mystery, known as the coronal heating problem, has challenged solar physicists since the mid-twentieth century (Klimchuk 2006). Two main explanations compete. In wave heating, magnetic waves generated below the surface travel upward and deposit their energy in the corona. In the nanoflare model, vast numbers of tiny magnetic reconnections release energy across the corona in frequent, small bursts (Klimchuk 2006). Most researchers now suspect both contribute, but the balance between them remains unresolved.`,
      `Coronal rain is not merely a curiosity, it is a direct diagnostic of this puzzle. Because the rain forms when hot coronal plasma cools and falls, tracking where, when, and how often it appears reveals how energy is being pumped into the corona in the first place (Antolin 2020). The July 2012 event gave researchers a particularly striking example.`,
    ],
  },
  {
    id: 3,
    orbLabel: 'Reading the July 2012 Event',
    modalTitle: 'Reading the July 2012 Event',
    x: 73,
    y: 19,
    size: 48,
    figure: {
      label: 'Figure 2',
      placeholder: 'Insert additional SDO magnetic-loop image here',
      videoSrc: MAGNETIC_VIDEO_SRC,
      caption:
        'Magnetic loops in the solar corona captured by NASA’s Solar Dynamics Observatory. The bright arcing structures trace the magnetic field lines that guide charged plasma through the corona, helping explain why coronal rain falls in curved streams rather than straight downward paths. Source: NASA/SDO (2015).',
      insertAfterParagraph: 3,
    },
    paragraphs: [
      `The rain in the APOD video did not appear out of nowhere. On 19 July 2012, an active region on the Sun's eastern limb, catalogued as AR11520, unleashed an M7.7-class solar flare and a coronal mass ejection. The Solar Dynamics Observatory recorded the aftermath in extreme ultraviolet light, and for roughly the next hour a cathedral of plasma glowed, cooled, and drained back to the surface.`,
      `Two physical processes turn that aftermath into the spectacle we see. The first is thermal instability. Coronal plasma is normally so hot that it radiates energy away slowly. But if a parcel of plasma cools slightly, perhaps because energy stops being pumped in at the same rate, it begins to radiate more efficiently at lower temperatures, which cools it further, which speeds up the radiation still more. The process runs away. In minutes, plasma that was a million degrees can plunge to a hundred thousand, then tens of thousands, condensing into dense blobs in a way genuinely analogous to water vapour condensing into droplets in Earth's atmosphere.`,
      `The second process explains the arcs. Plasma is made of charged particles, and charged particles cannot freely cross magnetic field lines, they are forced to slide along them, like beads threaded on wires. The corona is not a chaotic soup; it is a forest of magnetic loops, rooted in the photosphere and arching high above it. When a clump of cooled plasma begins to fall, gravity pulls it downward, but the magnetic field dictates the path. The rain does not drop straight. It follows the loops.`,
      `Figure 2 makes this architecture visible. The bright arcs in that image are the same kind of magnetic structures responsible for the motion in Figure 1: in Figure 2 they are lit up by hot plasma on the way up, and in Figure 1 cooler plasma is sliding back down them. Looking at the two side by side, the APOD video stops looking like a strange rainstorm and starts looking like exactly what it is, matter confined to an invisible magnetic skeleton, tracing the otherwise unseen shape of the Sun's atmosphere.`,
      `But the coronal rain was not the only thing the July 2012 eruption produced. It also fired something directly toward Earth.`,
    ],
  },
  {
    id: 4,
    orbLabel: 'Space Weather and Earth',
    modalTitle: 'Space Weather and Earth',
    x: 90,
    y: 43,
    size: 72,
    paragraphs: [
      `When a coronal mass ejection reaches Earth, its charged particles slam into our planet's magnetic field and can generate what space physicists call a geomagnetic storm. These storms induce currents in long conductors like power lines and pipelines, expose satellites to damaging particle bombardment, and degrade GPS accuracy and radio communications (NASA 2024b). The most extreme historical example is the 1859 Carrington Event, whose induced currents reportedly set telegraph offices on fire (Odenwald 2009). A storm of equivalent size today would affect systems ordinary life now depends on.`,
      `Solar activity is not constant. The Sun runs on an eleven-year cycle, swinging from quiet periods with few sunspots to active ones packed with flares and eruptions (NASA 2024a). In October 2024, NASA and NOAA confirmed that Solar Cycle 25 had reached its maximum (NASA 2024b). Forecasters had originally expected a mild cycle, comparable to the previous one; observations through 2024 showed it was considerably more energetic than predicted (NASA 2024b).`,
      `Australians had a front-row seat to what that looks like. In May 2024, active region AR13664 produced a barrage of X-class flares and coronal mass ejections, driving a G5-rated geomagnetic storm, the strongest since the Halloween storms of October 2003 (NASA 2024b). The Bureau of Meteorology's Space Weather Services, Australia's operational space weather forecaster, issued severe storm warnings across multiple successive days and reported high-frequency radio blackouts and widespread ionospheric disturbance (Bureau of Meteorology 2024). Aurora australis, normally confined to latitudes near Tasmania and the Southern Ocean, shimmered pink and green over Queensland and much of mainland Australia. Photographs from backyards and beaches filled social media. GPS-dependent farm equipment drifted off course. Power grid operators scrambled to monitor induced currents. For a few nights, the same physics on display in the APOD video, magnetic eruptions hurling plasma along invisible field lines, wrote itself across the skies above Sydney.`,
      `The cascade on the Sun and the glow over Australia are not separate phenomena. They are consequences of the same magnetic machinery, seen from different angles. To understand how coronal rain moves is to glimpse the rhythm behind much larger solar events.`,
    ],
  },
  {
    id: 5,
    orbLabel: 'What Coronal Rain Is Teaching Scientists Today',
    modalTitle: 'What Coronal Rain Is Teaching Scientists Today',
    x: 78,
    y: 70,
    size: 56,
    paragraphs: [
      `The 2024 storms showed how exposed we still are to the Sun's moods. A spacecraft launched four years earlier is showing how much we still do not understand about what drives those moods. Solar Orbiter is an ESA-led mission with NASA contributions, carrying instruments designed to study the Sun closer than any spacecraft before it (European Space Agency 2022). On its first close pass in March 2022, it swept to within about a third of the Earth–Sun distance and pointed its Extreme Ultraviolet Imager at a turbulent region near the solar surface.`,
      `The images transformed what coronal rain looks like. Solar Orbiter's High Resolution Imager can resolve features as small as 240 kilometres in extreme ultraviolet, a new benchmark for observations at such wavelengths (Antolin et al. 2023). Where earlier instruments showed fat ribbons of descending plasma, Solar Orbiter revealed that those ribbons are bundles of much finer threads, some only a few hundred kilometres wide. The rain has structure inside structure.`,
      `More importantly, the data uncovered something unexpected. Just beneath the falling clumps, the instruments caught brief flashes of ultraviolet brightening. The researchers interpret these as small-scale heating events, produced when the descending plasma compresses the gas directly below it (Antolin et al. 2023). The analogy they use is a meteor heating the air in front of itself as it plunges through the atmosphere. If the interpretation holds, coronal rain is not only a consequence of whatever heats the corona, it is also, in a small way, part of the heating itself, releasing stored energy on the way down.`,
      `Solar Orbiter's images are only half the story. A second spacecraft has been doing something even more audacious: flying through the corona itself. NASA's Parker Solar Probe, launched in 2018, was built for in-situ measurement, sampling the gas, feeling the magnetic field, and counting the charged particles that remote imaging can only infer (NASA 2024c). On Christmas Eve 2024, after seven Venus flybys gradually tightened its orbit, Parker reached its closest-ever approach, skimming just 6.1 million kilometres above the Sun's surface, about nine solar radii, at 692,000 kilometres per hour, the fastest any human-made object has ever travelled (NASA 2024c). A carbon-composite heat shield kept its instruments at room temperature while its forward face climbed toward 1,000 °C.`,
      `Where Solar Orbiter provides unprecedented pictures, Parker provides the physics underneath. Its instruments have revealed that the solar wind near the Sun is not a smooth outflow but is peppered with magnetic “switchbacks”, abrupt S-shaped reversals of the magnetic field, often lasting only seconds at a time (Bale et al. 2019). In 2023, the Parker team published evidence that these switchbacks are generated near the solar surface by small-scale magnetic reconnection events at the edges of coronal holes, large regions of open magnetic field from which most of the fast solar wind streams outward (Bale et al. 2023). That is exactly the kind of short-lived, small-scale process that might also be part of what heats the corona, bringing the nanoflare picture from Section 2 into the reach of direct measurement for the first time.`,
      `Together, the two missions are circling the same underlying mechanism from different angles. Solar Orbiter sees the consequences from close range: plasma cooling, compressing, raining back down in ultraviolet light. Parker measures the driving process directly: turbulent, switchback-laden magnetic fields carrying energy out from tiny reconnection events near the surface. Neither could build the case alone.`,
      `None of that was visible in the 2018 APOD. Each close pass by Solar Orbiter, and each dive through the corona by Parker, sharpens our picture of what that video was actually showing.`,
    ],
  },
  {
    id: 6,
    orbLabel: 'Conclusion',
    modalTitle: 'Conclusion',
    x: 38,
    y: 73,
    size: 52,
    paragraphs: [
      `Watch the clip again. What looked like falling water is plasma at fifty thousand degrees, sliding along magnetic rails through an atmosphere hotter than the surface below. The same eruptions that produce these graceful cascades can launch clouds across 150 million kilometres of space, light up Australian skies with aurora australis, and interfere with the satellites and power networks modern life runs on. And after seventy years of work, we still do not know exactly what keeps the corona so hot, or what role the rain itself plays in maintaining it. The Sun has been burning steadily for 4.6 billion years (NASA 2024a); systematic space-based observation of its atmosphere has been possible for only a few decades. Every close pass by Parker Solar Probe, every zoom-in by Solar Orbiter, reminds us how much of our nearest star we are still only beginning to see.`,
    ],
  },
  {
    id: 7,
    orbLabel: 'References & AI Acknowledgement',
    modalTitle: 'References & AI Acknowledgement',
    x: 14,
    y: 64,
    size: 46,
    paragraphs: [
      'AI acknowledgement: I used ChatGPT to assist with brainstorming structure, refining phrasing, and receiving feedback on clarity and presentation. I also used Claude to review drafts and suggest structural and stylistic improvements. All scientific content, factual claims, source selection, and final written interpretation were reviewed and verified by me against the cited sources.',
    ],
    references: [
      'Antolin, P., 2020. Thermal instability and non-equilibrium in solar coronal loops: from coronal rain to long-period intensity pulsations. Plasma Physics and Controlled Fusion, 62(1), 014016.',
      'Antolin, P., Martínez-Sykora, J., Sainz Dalda, A., Auchère, F., Berghmans, D., Mandal, S., Barczynski, K., Chitta, L.P., Peter, H., Teriaca, L., Schühle, U. and Harra, L., 2023. Extreme-ultraviolet fine structure and variability associated with coronal rain revealed by Solar Orbiter/EUI HRIEUV and SPICE. Astronomy & Astrophysics, 676, A112. Available at: https://www.aanda.org/articles/aa/full_html/2023/08/aa46016-23/ (Accessed 16 April 2026).',
      'Bale, S.D. et al., 2019. Highly structured slow solar wind emerging from an equatorial coronal hole. Nature, 576(7786), pp.237–242.',
      'Bale, S.D. et al., 2023. Interchange reconnection as the source of the fast solar wind within coronal holes. Nature, 618, pp.252–256.',
      'Bureau of Meteorology, 2024. Severe geomagnetic storm – May 2024. Space Weather Services, Australian Government. Available at: https://www.sws.bom.gov.au/ (Accessed 18 April 2026).',
      `European Space Agency, 2022. Solar Orbiter's first close encounter with the Sun. ESA, 25 March. Available at: https://www.esa.int/Science_Exploration/Space_Science/Solar_Orbiter (Accessed 16 April 2026).`,
      'Klimchuk, J.A., 2006. On solving the coronal heating problem. Solar Physics, 234(1), pp.41–77.',
      'NASA, 2018. Coronal Rain on the Sun. Astronomy Picture of the Day, 27 May. Available at: https://apod.nasa.gov/apod/ap180527.html (Accessed 16 April 2026).',
      'NASA, 2024a. The Sun. NASA Science. Available at: https://science.nasa.gov/sun/ (Accessed 16 April 2026).',
      'NASA, 2024b. NASA, NOAA: Sun Reaches Maximum Phase in 11-Year Solar Cycle. NASA Science, 15 October. Available at: https://science.nasa.gov/science-research/heliophysics/nasa-noaa-sun-reaches-maximum-phase-in-11-year-solar-cycle/ (Accessed 16 April 2026).',
      "NASA, 2024c. NASA's Parker Solar Probe Makes History With Closest Pass to Sun. NASA Science, 27 December. Available at: https://science.nasa.gov/science-research/heliophysics/nasas-parker-solar-probe-makes-history-with-closest-pass-to-sun/ (Accessed 19 April 2026).",
      'NASA/SDO, 2015. Solar Dynamics Observatory imagery archive. NASA Goddard Space Flight Center. Available at: https://sdo.gsfc.nasa.gov/gallery/main (Accessed 16 April 2026).',
      'Odenwald, S., 2009. The Day the Sun Brought Darkness. NASA, 13 March. Available at: https://www.nasa.gov/science-research/heliophysics/the-day-the-sun-brought-darkness/ (Accessed 18 April 2026).',
      'OpenAI, 2026. ChatGPT [ChatGPT 5.4]. Retrieved 17 April 2026 from https://chatgpt.com/.',
      'Anthropic, 2026. Claude [Claude Opus 4.7]. Retrieved 19 April 2026 from https://claude.ai/.',
      'Reale, F., 2014. Coronal loops: observations and modeling of confined plasma. Living Reviews in Solar Physics, 11(1), 4.',
    ],
  },
];
